services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: healio
    ports:
      - '5432:5432'
    volumes:
      - healio_pg:/var/lib/postgresql/data

volumes:
  healio_pg:
